### ISSUE TITLE
SSH auth fails due to permission issue with pubkey. 

### ISSUE THREAD

**Issue by rustyguts** [carlalexander/debops-wordpress#162] opened 2017-05-12 03:32 UTC
Hello.

I have followed the steps exactly as documented. I get to...
`debops bootstrap -u root`

---

```brendan@wordpress:~/debops-wordpress$ debops bootstrap -u root -vvvv
Running Ansible playbook from:
/home/brendan/.local/share/debops/debops-playbooks/playbooks/bootstrap.yml ...
Using /home/brendan/debops-wordpress/ansible.cfg as config file
statically included: /home/brendan/.local/share/debops/debops-playbooks/roles/debops.bootstrap/tasks/admin_accounts.yml
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: bootstrap.yml ********************************************************
2 plays in /home/brendan/.local/share/debops/debops-playbooks/playbooks/bootstrap.yml

PLAY [Bootstrap Python support on a host] **************************************
META: ran handlers

TASK [debops.bootstrap/raw : Update APT repositories, install mandatory packages] ***
task path: /home/brendan/.local/share/debops/debops-playbooks/roles/debops.bootstrap/raw/tasks/main.yml:3
<wordpress.whitkennedy.com> ESTABLISH SSH CONNECTION FOR USER: root
<wordpress.whitkennedy.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/brendan/.ansible/cp/4de5e62330 -tt wordpress.whitkennedy.com 'apt-get update ; apt-get --no-install-recommends -yq install python python-apt'
<wordpress.whitkennedy.com> (255, '', 'OpenSSH_7.2p2 Ubuntu-4ubuntu2.2, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/home/brendan/.ansible/cp/4de5e62330" does not exist\r\ndebug2: resolving "wordpress.whitkennedy.com" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to wordpress.whitkennedy.com [127.0.1.1] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 9994 ms remain after connect\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_rsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_rsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_dsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_dsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_ecdsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_ecdsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_ed25519 type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_ed25519-cert type -1\r\ndebug1: Enabling compatibility mode for protocol 2.0\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2\r\ndebug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.2\r\ndebug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.2 pat OpenSSH* compat 0x04000000\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: Authenticating to wordpress.whitkennedy.com:22 as \'root\'\r\ndebug3: hostkeys_foreach: reading file "/home/brendan/.ssh/known_hosts"\r\ndebug3: record_hostkey: found key type ECDSA in file /home/brendan/.ssh/known_hosts:1\r\ndebug3: load_hostkeys: loaded 1 keys from wordpress.whitkennedy.com\r\ndebug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521\r\ndebug3: send packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug3: receive packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug2: local client KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c\r\ndebug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: zlib@openssh.com,zlib,none\r\ndebug2: compression stoc: zlib@openssh.com,zlib,none\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug2: peer server KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1\r\ndebug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: none,zlib@openssh.com\r\ndebug2: compression stoc: none,zlib@openssh.com\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug1: kex: algorithm: curve25519-sha256@libssh.org\r\ndebug1: kex: host key algorithm: ecdsa-sha2-nistp256\r\ndebug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug3: send packet: type 30\r\ndebug1: expecting SSH2_MSG_KEX_ECDH_REPLY\r\ndebug3: receive packet: type 31\r\ndebug1: Server host key: ecdsa-sha2-nistp256 SHA256:xlw3NBrndjx6skzTPbrazLNS/xqv2tfCEu/D7ytGkSw\r\ndebug3: hostkeys_foreach: reading file "/home/brendan/.ssh/known_hosts"\r\ndebug3: record_hostkey: found key type ECDSA in file /home/brendan/.ssh/known_hosts:1\r\ndebug3: load_hostkeys: loaded 1 keys from wordpress.whitkennedy.com\r\ndebug1: Host \'wordpress.whitkennedy.com\' is known and matches the ECDSA host key.\r\ndebug1: Found key in /home/brendan/.ssh/known_hosts:1\r\ndebug3: send packet: type 21\r\ndebug2: set_newkeys: mode 1\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug3: receive packet: type 21\r\ndebug2: set_newkeys: mode 0\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug2: key: /home/brendan/.ssh/id_rsa ((nil))\r\ndebug2: key: /home/brendan/.ssh/id_dsa ((nil))\r\ndebug2: key: /home/brendan/.ssh/id_ecdsa ((nil))\r\ndebug2: key: /home/brendan/.ssh/id_ed25519 ((nil))\r\ndebug3: send packet: type 5\r\ndebug3: receive packet: type 7\r\ndebug1: SSH2_MSG_EXT_INFO received\r\ndebug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>\r\ndebug3: receive packet: type 6\r\ndebug2: service_accept: ssh-userauth\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\ndebug3: send packet: type 50\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey\r\ndebug3: start over, passed a different list publickey\r\ndebug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_lookup publickey\r\ndebug3: remaining preferred: ,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_is_enabled publickey\r\ndebug1: Next authentication method: publickey\r\ndebug1: Trying private key: /home/brendan/.ssh/id_rsa\r\ndebug3: no such identity: /home/brendan/.ssh/id_rsa: No such file or directory\r\ndebug1: Trying private key: /home/brendan/.ssh/id_dsa\r\ndebug3: no such identity: /home/brendan/.ssh/id_dsa: No such file or directory\r\ndebug1: Trying private key: /home/brendan/.ssh/id_ecdsa\r\ndebug3: no such identity: /home/brendan/.ssh/id_ecdsa: No such file or directory\r\ndebug1: Trying private key: /home/brendan/.ssh/id_ed25519\r\ndebug3: no such identity: /home/brendan/.ssh/id_ed25519: No such file or directory\r\ndebug2: we did not send a packet, disable method\r\ndebug1: No more authentication methods to try.\r\nPermission denied (publickey).\r\n')
fatal: [wordpress.whitkennedy.com]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.2p2 Ubuntu-4ubuntu2.2, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/home/brendan/.ansible/cp/4de5e62330\" does not exist\r\ndebug2: resolving \"wordpress.whitkennedy.com\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to wordpress.whitkennedy.com [127.0.1.1] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 9994 ms remain after connect\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_rsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_rsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_dsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_dsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_ecdsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_ecdsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_ed25519 type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/brendan/.ssh/id_ed25519-cert type -1\r\ndebug1: Enabling compatibility mode for protocol 2.0\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2\r\ndebug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.2\r\ndebug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.2 pat OpenSSH* compat 0x04000000\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: Authenticating to wordpress.whitkennedy.com:22 as 'root'\r\ndebug3: hostkeys_foreach: reading file \"/home/brendan/.ssh/known_hosts\"\r\ndebug3: record_hostkey: found key type ECDSA in file /home/brendan/.ssh/known_hosts:1\r\ndebug3: load_hostkeys: loaded 1 keys from wordpress.whitkennedy.com\r\ndebug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521\r\ndebug3: send packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug3: receive packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug2: local client KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c\r\ndebug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: zlib@openssh.com,zlib,none\r\ndebug2: compression stoc: zlib@openssh.com,zlib,none\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug2: peer server KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1\r\ndebug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: none,zlib@openssh.com\r\ndebug2: compression stoc: none,zlib@openssh.com\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug1: kex: algorithm: curve25519-sha256@libssh.org\r\ndebug1: kex: host key algorithm: ecdsa-sha2-nistp256\r\ndebug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug3: send packet: type 30\r\ndebug1: expecting SSH2_MSG_KEX_ECDH_REPLY\r\ndebug3: receive packet: type 31\r\ndebug1: Server host key: ecdsa-sha2-nistp256 SHA256:xlw3NBrndjx6skzTPbrazLNS/xqv2tfCEu/D7ytGkSw\r\ndebug3: hostkeys_foreach: reading file \"/home/brendan/.ssh/known_hosts\"\r\ndebug3: record_hostkey: found key type ECDSA in file /home/brendan/.ssh/known_hosts:1\r\ndebug3: load_hostkeys: loaded 1 keys from wordpress.whitkennedy.com\r\ndebug1: Host 'wordpress.whitkennedy.com' is known and matches the ECDSA host key.\r\ndebug1: Found key in /home/brendan/.ssh/known_hosts:1\r\ndebug3: send packet: type 21\r\ndebug2: set_newkeys: mode 1\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug3: receive packet: type 21\r\ndebug2: set_newkeys: mode 0\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug2: key: /home/brendan/.ssh/id_rsa ((nil))\r\ndebug2: key: /home/brendan/.ssh/id_dsa ((nil))\r\ndebug2: key: /home/brendan/.ssh/id_ecdsa ((nil))\r\ndebug2: key: /home/brendan/.ssh/id_ed25519 ((nil))\r\ndebug3: send packet: type 5\r\ndebug3: receive packet: type 7\r\ndebug1: SSH2_MSG_EXT_INFO received\r\ndebug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>\r\ndebug3: receive packet: type 6\r\ndebug2: service_accept: ssh-userauth\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\ndebug3: send packet: type 50\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey\r\ndebug3: start over, passed a different list publickey\r\ndebug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_lookup publickey\r\ndebug3: remaining preferred: ,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_is_enabled publickey\r\ndebug1: Next authentication method: publickey\r\ndebug1: Trying private key: /home/brendan/.ssh/id_rsa\r\ndebug3: no such identity: /home/brendan/.ssh/id_rsa: No such file or directory\r\ndebug1: Trying private key: /home/brendan/.ssh/id_dsa\r\ndebug3: no such identity: /home/brendan/.ssh/id_dsa: No such file or directory\r\ndebug1: Trying private key: /home/brendan/.ssh/id_ecdsa\r\ndebug3: no such identity: /home/brendan/.ssh/id_ecdsa: No such file or directory\r\ndebug1: Trying private key: /home/brendan/.ssh/id_ed25519\r\ndebug3: no such identity: /home/brendan/.ssh/id_ed25519: No such file or directory\r\ndebug2: we did not send a packet, disable method\r\ndebug1: No more authentication methods to try.\r\nPermission denied (publickey).\r\n",
    "unreachable": true
}
 [WARNING]: Could not create retry file '/home/brendan/.local/share/debops
/debops-playbooks/playbooks/bootstrap.retry'.         [Errno 13] Permission
denied: u'/home/brendan/.local/share/debops/debops-
playbooks/playbooks/bootstrap.retry'


PLAY RECAP *********************************************************************
wordpress.whitkennedy.com  : ok=0    changed=0    unreachable=1    failed=0

TASK: debops.bootstrap/raw : Update APT repositories, install mandatory packages --- 0.28s
```

---

I have tried using the server IP address in the inventory/hosts file
I have tried running as sudo user and as root user. 

Server is Ubuntu 16.04 LTS with one sudo user, no firewall enabled, fresh install. Followed DebOps guide to the T. 

I'm just not sure what this error means or how to fix it. I apologize for sounding incompetent but I'm just missing what is wrong here.

**Comment by MiteshShah** [comment] 2017-05-12 18:18
> Connecting to wordpress.whitkennedy.com [127.0.1.1] port 22

From terminal are you able to ssh?
`ssh root@wordpress.whitkennedy.com`
or
`ssh root@127.0.1.1`

**Comment by rustyguts** [comment] 2017-05-12 18:47
@MiteshShah  Yes I am. Both work but require my password  to authenticate. I usually have passwords turned off but right now I am trying anything 

I'm guessing I am not configuring SSH correctly? 

I spawned my server with user root and my public key on server. I login with ssh and my private key and add sudo user with same pub/priv key. I then disabled password authentication. So when I login, all I need to enter is my priv key passphrase.

**Comment by MiteshShah** [comment] 2017-05-12 18:55
@RustyGuts Check this https://github.com/ansible/ansible/issues/2155

First, add your ssh passphrase to ssh-agent so its remember it and you are directly login into a server.

Make sure when you fire `ssh root@wordpress.whitkennedy.com` or `ssh root@127.0.1.1` you are directly login into server its does not ask for any password/passphrase.

**Comment by rustyguts** [comment] 2017-05-12 19:12
@MiteshShah  Thanks for the help. 

`brendan@wordpress:~$ ssh-agent bash`
`brendan@wordpress:~$ ssh-add ~/.ssh/authorized_keys`
`Enter passphrase for /home/brendan/.ssh/authorized_keys:`
`Bad passphrase, try again for /home/brendan/.ssh/authorized_keys:`

I'm not a unix admin but I do not store my private key on the server, correct? authorized_keys just has my public key in it. I have no idea why its saying bad passphrase. 

sshd_config has these settings

`PasswordAuthentication no`
`PubkeyAuthentication yes`
`ChallengeResponseAuthentication no`

**Comment by MiteshShah** [comment] 2017-05-12 19:14
> I'm not a unix admin but I do not store my private key on the server, correct? authorized_keys just has my public key in it. I have no idea why its saying bad passphrase.

Yes

Bad Passphrase means you enter wrong details imagine you are trying to login into Gmail and due to some typo mistake Gmail told wrong username or password.

**Comment by rustyguts** [comment] 2017-05-12 19:32
@MiteshShah  

I've tried my password 20 times. I even regenerated a new key pair and made absolute certain I knew the password. I can't believe how stuck I am!

I use Putty to connect. I can login with Putty using my passphrase no issues. however, with sshd password authentication turned **Off** when I run 
`ssh root@wordpress.whitkennedy.com`
I get 
`Permission denied (publickey).`

So I'm confused as to how Putty can connect with passphrase but I can't ssh once I am in.

**Comment by rustyguts** [comment] 2017-05-12 20:40
Well I tried uploading my private key to the server. 

`ssh root@wordpress.whitkennedy.com -i /root/.ssh/id_rsa -v`

Even then it says my passphrase is wrong. I have absolute no idea why. I am entering my passphrase exactly as it is written. 

```
debug1: Found key in /root/.ssh/known_hosts:1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /root/.ssh/id_rsa
Enter passphrase for key '/root/.ssh/id_rsa':
Enter passphrase for key '/root/.ssh/id_rsa':
Enter passphrase for key '/root/.ssh/id_rsa':
debug1: No more authentication methods to try.
Permission denied (publickey).
```

**Comment by carlalexander** [comment] 2017-05-12 21:06
There's no bad question. 😄 

Are you trying to do this on your server or your computer? This is an issue with your computer. `-i` should point to `id_rsa` on your computer.

I wrote a [guide](https://carlalexander.ca/2016-macbook-pro-setup/) on how I setup my McaBook. You can check the section on SSH to see how I configured `ssh-agent` on it.

**Comment by wpbullet** [comment] 2017-05-12 21:08
I wanted to chime in here as ssh auth errors can be a major pain to diagnose mainly because the errors reported in logs do not necessarily reflect the actual problem. Usually it is a problem with the key itself or the permissions. I would personally test without a passphrase before attempting with a passphrase.

**Comment by rustyguts** [comment] 2017-05-12 23:04
I am doing this from the webserver itself. Many of the guides I have been following do not comment when they switch from webserver to local computer and that has confused me in a few ways. 

Also I have been using putty keys with the notion that they were not edited in any ways. I found that Putty keys do not contain the original information and need to be converted in order for Ansbile to work properly with SSH. 

I am running through the instillation now with proper SSH keys not generated for PUTTY.

**Comment by rustyguts** [comment] 2017-05-12 23:06
Yay! I've created my first aDebOps site. 

One thing I noticed is that the nginx root is /var/www/html and ansible has installed WP to /var/www/example.com

I currently can only see the index page. I'm sure this is an easy fix?
[site](http://wordpress.whitkennedy.com)
@carlalexander

**Comment by carlalexander** [comment] 2017-05-14 16:45
I can't see anything @RustyGuts

**Comment by elvtn** [comment] 2017-06-06 13:54
FYI, I was having the same issue on an Ubuntu 16.04 droplet:

    TASK [debops.bootstrap/raw : Update APT repositories, install mandatory packages] 
    ********************************************************************************************
    fatal: [dev.hostname.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect 
    to the host via ssh: Permission denied (publickey).\r\n", "unreachable": true}
	to retry, use: --limit @/root/.local/share/debops/debops-playbooks/playbooks/bootstrap.retry

I was unable to SSH locally either:

    root@dev:~/.ssh# ssh root@127.0.0.1
    The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
    ECDSA key fingerprint is SHA256:*************************************************.
    Are you sure you want to continue connecting (yes/no)? yes
    Warning: Permanently added '127.0.0.1' (ECDSA) to the list of known hosts.
    Permission denied (publickey).

I confirmed I had valid SSH keys with correct permissions:

    root@dev:~/.ssh# ls -al
    total 28
    drwx------ 2 root root 4096 Jun  6 13:30 .
    drwx------ 8 root root 4096 Jun  6 13:30 ..
    -rw------- 1 root root  808 Jun  6 13:43 authorized_keys
    -rw------- 1 root root 1675 Jun  6 13:20 id_rsa
    -rw-r--r-- 1 root root  390 Jun  6 13:20 id_rsa.pub
    -rw------- 1 root root  444 Jun  6 13:43 known_hosts

The fix was to add the public key into the authorized_keys file:

    root@dev:~/.ssh# cat id_rsa.pub >> authorized_keys

Now local SSH works:

    root@dev:~/.ssh# ssh root@127.0.0.1
    Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-78-generic x86_64)

And subsequently, the debops commands worked as well.

**Comment by rustyguts** [comment] 2017-06-07 02:19
@elvtn Thanks for the update. I will try this soon

**Comment by carlalexander** [comment] 2017-06-08 07:51
Are you running debops on the droplet?

**Comment by carlalexander** [comment] 2017-07-24 01:11
Going to close this for now. Feel free to reopen the issue if it still isn't working @whitkennedy 😃

**Closed as completed by carlalexander** 2017-07-24 01:11 UTC
Labels: awaiting feedback
