### ISSUE TITLE
`TASK [debops.pki : Initialize PKI authorities] *********************************

### ISSUE THREAD

**Issue by rukawaxz** [carlalexander/debops-wordpress#48] opened 2016-02-29 19:56 UTC
I get this error after sending command debops in the terminal.
`TASK [debops.pki : Initialize PKI authorities] *********************************
failed: [46.101.101.63 -> localhost] => (item={u'subdomain': u'root-ca', u'name': u'root', u'subject': [u'o=Ubuntu-worddebo-fra1-01 Certificate Authority']}) => {"changed": true, "cmd": ["./lib/pki-authority", "init", "--name", "root", "--default-sign-base", "365", "--root-sign-multiplier", "12", "--ca-sign-multiplier", "10", "--cert-sign-multiplier", "3"], "delta": "0:00:00.134644", "end": "2016-02-29 15:31:38.885341", "failed": true, "item": {"name": "root", "subdomain": "root-ca", "subject": ["o=Ubuntu-worddebo-fra1-01 Certificate Authority"]}, "rc": 2, "start": "2016-02-29 15:31:38.750697", "stderr": "./lib/pki-authority: line 77: declare: -g: invalid option\ndeclare: usage: declare [-afFirtx] [-p] [name[=value] ...]", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [46.101.101.63 -> localhost] => (item={u'subdomain': u'domain-ca', u'name': u'domain', u'issuer_name': u'root', u'subject': [u'o=Ubuntu-worddebo-fra1-01', u'ou=Domain CA']}) => {"changed": true, "cmd": ["./lib/pki-authority", "init", "--name", "domain", "--default-sign-base", "365", "--root-sign-multiplier", "12", "--ca-sign-multiplier", "10", "--cert-sign-multiplier", "3"], "delta": "0:00:00.015934", "end": "2016-02-29 15:31:39.063942", "failed": true, "item": {"issuer_name": "root", "name": "domain", "subdomain": "domain-ca", "subject": ["o=Ubuntu-worddebo-fra1-01", "ou=Domain CA"]}, "rc": 2, "start": "2016-02-29 15:31:39.048008", "stderr": "./lib/pki-authority: line 77: declare: -g: invalid option\ndeclare: usage: declare [-afFirtx] [-p] [name[=value] ...]", "stdout": "", "stdout_lines": [], "warnings": []}
skipping: [46.101.101.63] => (item={u'type': u'service', u'subdomain': u'service-ca', u'enabled': False, u'name': u'service', u'subject': [u'o=Ubuntu-worddebo-fra1-01', u'ou=Internal Services CA']})`

**Comment by drybjed** [comment] 2016-02-29 21:02
Are you using MacOS X as the Ansible Controller? You need to upgrade the `bash` to at least 4.3 so that the `pki-authority` script will work. It requires associative array support in the shell.

**Comment by carlalexander** [comment] 2016-02-29 22:05
I had a workaround for this issue that I was testing. I just committed it. Can you update the project and try again?

**Comment by rukawaxz** [comment] 2016-02-29 22:57
I used the brew install bash command to install latest version. Then changed the command path to /usr/local/bin/bash 
Still I had error.
I deleted the file and downloaded the project again now I get this error.

fatal: [46.101.101.63 -> localhost]: FAILED! => {"changed": false, "cmd": ["./lib/pki-authority", "sign-by-host", "ubuntu-wordDebo-fra1-01"], "delta": "0:00:00.083553", "end": "2016-02-29 18:44:17.819914", "failed": true, "rc": 2, "start": "2016-02-29 18:44:17.736361", "stderr": "./lib/pki-authority: line 77: declare: -g: invalid option\ndeclare: usage: declare [-afFirtx] [-p] [name[=value] ...]", "stdout": "", "stdout_lines": [], "warnings": []}

I am sending the command debops in OSX using both terminal and iterm and both give same error. My server is on digital ocean.

**Comment by rukawaxz** [comment] 2016-02-29 23:05
`Christians-MacBook-Pro:debops-wordpress christianlaborde$ sudo debops
Password:
Running Ansible playbook from:
/Users/christianlaborde/Library/Application Support/debops/debops-playbooks/playbooks/site.yml ...
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default). This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

PLAY [Prepare core environment] ************************************************

TASK [setup] *******************************************************************
ok: [46.101.101.63]

TASK [debops.core : Create root directories] ***********************************
ok: [46.101.101.63] => (item={u'path': u'/etc/ansible/facts.d', u'fact': u'facts'})
ok: [46.101.101.63] => (item={u'path': u'/usr/local/bin', u'fact': u'bin'})
ok: [46.101.101.63] => (item={u'path': u'/usr/local/etc', u'fact': u'etc'})
ok: [46.101.101.63] => (item={u'path': u'/usr/local/lib', u'fact': u'lib'})
ok: [46.101.101.63] => (item={u'path': u'/usr/local/sbin', u'fact': u'sbin'})
ok: [46.101.101.63] => (item={u'path': u'/usr/local/share', u'fact': u'share'})
ok: [46.101.101.63] => (item={u'path': u'/usr/local/src', u'fact': u'src'})
ok: [46.101.101.63] => (item={u'path': u'/srv', u'fact': u'data'})
ok: [46.101.101.63] => (item={u'path': u'/srv', u'fact': u'srv'})
ok: [46.101.101.63] => (item={u'path': u'/var/backups', u'fact': u'backup'})
ok: [46.101.101.63] => (item={u'path': u'/var/local', u'fact': u'home'})
ok: [46.101.101.63] => (item={u'path': u'/var/local', u'fact': u'app'})
ok: [46.101.101.63] => (item={u'path': u'/var/local', u'fact': u'var'})
ok: [46.101.101.63] => (item={u'path': u'/var/log', u'fact': u'log'})

TASK [debops.core : Check IP address of current Ansible Controller] ************
ok: [46.101.101.63]

TASK [debops.core : Read the host UUID] ****************************************
ok: [46.101.101.63]

TASK [debops.core : Save local facts] ******************************************
ok: [46.101.101.63] => (item=core)
ok: [46.101.101.63] => (item=root)
ok: [46.101.101.63] => (item=tags)
ok: [46.101.101.63] => (item=uuid)

TASK [debops.core : Install local fact scripts] ********************************
ok: [46.101.101.63]

TASK [debops.core : Gather local facts if they changed] ************************
skipping: [46.101.101.63]

TASK [debops.core : Update APT cache and install required packages] ************
ok: [46.101.101.63] => (item=[u'libcap2-bin'])

PLAY [Common configuration for all hosts] **************************************

TASK [setup] *******************************************************************
ok: [46.101.101.63]

TASK [debops.pki/env : Prepare debops.pki environment] *************************
ok: [46.101.101.63]

TASK [debops.secret : Create secret directories on Ansible Controller] *********
ok: [46.101.101.63 -> localhost] => (item=pki/lib)
ok: [46.101.101.63 -> localhost] => (item=pki/ca-certificates/by-host/ubuntu-wordDebo-fra1-01)
ok: [46.101.101.63 -> localhost] => (item=pki/ca-certificates/by-group/all)
ok: [46.101.101.63 -> localhost] => (item=pki/ca-certificates/by-group/debops_service_pki)
ok: [46.101.101.63 -> localhost] => (item=pki/realms/by-group/all/domain/external)
ok: [46.101.101.63 -> localhost] => (item=pki/realms/by-group/all/domain/private)
ok: [46.101.101.63 -> localhost] => (item=pki/realms/by-host/ubuntu-wordDebo-fra1-01/domain/external)
ok: [46.101.101.63 -> localhost] => (item=pki/realms/by-host/ubuntu-wordDebo-fra1-01/domain/internal)
ok: [46.101.101.63 -> localhost] => (item=pki/realms/by-host/ubuntu-wordDebo-fra1-01/domain/private)

TASK [debops.apt_preferences : Remove APT preferences] *************************
skipping: [46.101.101.63] => (item={u'reason': u'Version parity with Debian Jessie, support for AuthorizedKeysCommand, better ciphers', u'by_role': u'debops.sshd', u'backports': [u'wheezy'], u'package': u'ssh ssh-\* openssh-*'}) 

TASK [debops.apt_preferences : Create APT preferences] *************************
skipping: [46.101.101.63] => (item={u'reason': u'Version parity with Debian Jessie, support for AuthorizedKeysCommand, better ciphers', u'by_role': u'debops.sshd', u'backports': [u'wheezy'], u'package': u'ssh ssh-\* openssh-*'}) 

TASK [debops.etc_services : Make sure /etc/services.d directory exists] ********
ok: [46.101.101.63]

TASK [debops.etc_services : Create /etc/services.d/00_ansible] *****************
ok: [46.101.101.63]

TASK [debops.etc_services : Divert original /etc/services] *********************
ok: [46.101.101.63]

TASK [debops.etc_services : Generate list of local services if requested] ******

TASK [debops.etc_services : Assemble /etc/services.d] **************************
ok: [46.101.101.63]

TASK [debops.etc_services : Move current /etc/services out of the way before reversion] ***
skipping: [46.101.101.63]

TASK [debops.etc_services : Remove diversion of /etc/services] *****************
skipping: [46.101.101.63]

TASK [debops.atd : Install atd] ************************************************
ok: [46.101.101.63]

TASK [debops.atd : Generate consistent atd variables] **************************
ok: [46.101.101.63]

TASK [debops.atd : Configure atd and batch] ************************************
ok: [46.101.101.63]

TASK [debops.atd : Install custom atd init script] *****************************
skipping: [46.101.101.63]

TASK [debops.atd : Install custom atd.service unit] ****************************
ok: [46.101.101.63]

TASK [debops.atd : Configure /etc/at.allow] ************************************
ok: [46.101.101.63] => (item=root)

TASK [debops.atd : Remove /etc/at.allow if list is empty] **********************
skipping: [46.101.101.63]

TASK [debops.atd : Configure /etc/at.deny] *************************************

TASK [debops.atd : Make sure that Ansible local facts directory exists] ********
ok: [46.101.101.63]

TASK [debops.atd : Save atd facts] *********************************************
ok: [46.101.101.63]

TASK [debops.atd : Gather Ansible facts if needed] *****************************
skipping: [46.101.101.63]

TASK [debops.secret : Create secret directories on Ansible Controller] *********

TASK [debops.dhparam : Check Ansible Controller library version] ***************
ok: [46.101.101.63 -> localhost]

TASK [debops.dhparam : Assert that required software is installed] *************
ok: [46.101.101.63 -> localhost]

TASK [debops.dhparam : Create required directories on Ansible Controller] ******
ok: [46.101.101.63 -> localhost]

TASK [debops.dhparam : Generate Diffie-Hellman params on Ansible Controller] ***
ok: [46.101.101.63 -> localhost] => (item=3072)

TASK [debops.dhparam : Install encryption software] ****************************
ok: [46.101.101.63] => (item=[u'openssl', u'cron'])

TASK [debops.dhparam : Create required directories] ****************************
ok: [46.101.101.63]

TASK [debops.dhparam : Preseed Diffie-Hellman parameters] **********************
ok: [46.101.101.63] => (item=0)

TASK [debops.dhparam : Create default symlinks for all sets] *******************
ok: [46.101.101.63] => (item=0)

TASK [debops.dhparam : Install DHE generation script] **************************
ok: [46.101.101.63]

TASK [debops.dhparam : Enable periodic DH parameters generation] ***************
ok: [46.101.101.63]

TASK [debops.dhparam : Make sure the Ansible local facts directory exists] *****
ok: [46.101.101.63]

TASK [debops.dhparam : Save dhparam local facts] *******************************
ok: [46.101.101.63]

TASK [debops.dhparam : Gather facts if they changed] ***************************
skipping: [46.101.101.63]

TASK [debops.secret : Create secret directories on Ansible Controller] *********

TASK [debops.pki : Expose host FQDN in temporary variable] *********************
ok: [46.101.101.63]

TASK [debops.pki : Install PKI packages] ***************************************
skipping: [46.101.101.63] => (item=[]) 

TASK [debops.pki : Create library directory] ***********************************
skipping: [46.101.101.63]

TASK [debops.pki : Install local PKI scripts] **********************************
ok: [46.101.101.63 -> localhost]

TASK [debops.pki : Install remote PKI scripts] *********************************
skipping: [46.101.101.63]

TASK [debops.pki : Create private groups if requested] *************************

TASK [debops.pki : Configure acme-tiny support] ********************************
skipping: [46.101.101.63]

TASK [debops.pki : Initialize PKI realms] **************************************
skipping: [46.101.101.63] => (item={u'name': u'domain', u'acme': False}) 

TASK [debops.pki : Download custom private files] ******************************

TASK [debops.pki : Download private realm contents by host] ********************
skipping: [46.101.101.63] => (item={u'name': u'domain', u'acme': False}) 

TASK [debops.pki : Download private realm contents by group] *******************

TASK [debops.pki : Download private realm contents for all hosts] **************
skipping: [46.101.101.63] => (item={u'name': u'domain', u'acme': False}) 

TASK [debops.pki : Create PKI realms] ******************************************
skipping: [46.101.101.63] => (item={u'name': u'domain', u'acme': False}) 

TASK [debops.pki : Execute PKI realm commands] *********************************
skipping: [46.101.101.63] => (item={u'name': u'domain', u'acme': False}) 

TASK [debops.pki : Upload internal certificate requests] ***********************
skipping: [46.101.101.63] => (item={u'name': u'domain', u'acme': False}) 

TASK [debops.pki : Initialize PKI authorities] *********************************

TASK [debops.pki : Create PKI authorities] *************************************

TASK [debops.pki : Sign certificate requests for current hosts] ****************
fatal: [46.101.101.63 -> localhost]: FAILED! => {"changed": false, "cmd": ["./lib/pki-authority", "sign-by-host", "ubuntu-wordDebo-fra1-01"], "delta": "0:00:00.085978", "end": "2016-02-29 19:02:53.589505", "failed": true, "rc": 2, "start": "2016-02-29 19:02:53.503527", "stderr": "./lib/pki-authority: line 77: declare: -g: invalid option\ndeclare: usage: declare [-afFirtx] [-p] [name[=value] ...]", "stdout": "", "stdout_lines": [], "warnings": []}

PLAY RECAP *********************************************************************
46.101.101.63              : ok=35   changed=0    unreachable=0    failed=1   `

**Comment by carlalexander** [comment] 2016-02-29 23:32
If you updated bash, you need to restart your terminal window for the
change to take effect.

**Comment by rukawaxz** [comment] 2016-03-01 13:43
http://prntscr.com/a9tjpo
1) Created Digital ocean server
2) Edited Host file with new ip
3)cd debops-wordpress/
4) sudo debops -u root
5) yes continue
6)
`TASK [debops.pki : Sign certificate requests for current hosts] ****************
fatal: [46.101.235.48 -> localhost]: FAILED! => {"changed": false, "cmd": ["./lib/pki-authority", "sign-by-host", "ubuntu-debo-fra1-01"], "delta": "0:00:00.191360", "end": "2016-03-01 09:42:26.144747", "failed": true, "rc": 2, "start": "2016-03-01 09:42:25.953387", "stderr": "./lib/pki-authority: line 77: declare: -g: invalid option\ndeclare: usage: declare [-afFirtx] [-p] [name[=value] ...]", "stdout": "", "stdout_lines": [], "warnings": []}
`

**Comment by drybjed** [comment] 2016-03-01 13:49
@rukawaxz Try running:

```
/usr/bin/env bash
```

Which shell do you get? Also, what's the contents of your account `$PATH` variable?

**Comment by rukawaxz** [comment] 2016-03-01 14:18
result is
Christians-MacBook-Pro:debops-wordpress christianlaborde$ /usr/bin/env bash
bash-3.2$
Do you mean Christians-MacBook-Pro:~ christianlaborde$ echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

On Tue, Mar 1, 2016 at 9:49 AM, Maciej Delmanowski <notifications@github.com

**Comment by rukawaxz** [comment] 2016-03-01 14:23
I followed this tutorial to update bash 
http://buddylindsey.com/upgrade-bash-to-4-on-os-x/
and this one
http://clubmate.fi/upgrade-to-bash-4-in-mac-os-x/
I must be missing something right?
I also read and followed
http://superuser.com/questions/857250/how-to-update-bash-on-mac-os-x-yosemite
and this one 
http://apple.stackexchange.com/questions/193411/update-bash-to-version-4-0-on-osx

**Comment by drybjed** [comment] 2016-03-01 14:24
@rukawaxz Could you try moving the `/usr/local/bin` directory to the beginning of `$PATH` variable? This should make the GNU bash be the default one, hopefully it won't break your system too much. You will probably need to re-login to activate the updated shell.

**Comment by rukawaxz** [comment] 2016-03-01 15:34
TASK [debops.pki : Sign certificate requests for current hosts] ****************
fatal: [46.101.235.48 -> localhost]: FAILED! => {"changed": false, "cmd": ["./lib/pki-authority", "sign-by-host", "ubuntu-debo-fra1-01"], "delta": "0:00:00.218474", "end": "2016-03-01 11:33:00.131907", "failed": true, "rc": 2, "start": "2016-03-01 11:32:59.913433", "stderr": "./lib/pki-authority: line 77: declare: -g: invalid option\ndeclare: usage: declare [-afFirtx] [-p] [name[=value] ...]", "stdout": "", "stdout_lines": [], "warnings": []}

PLAY RECAP *********************************************************************
46.101.235.48              : ok=35   changed=0    unreachable=0    failed=1   

Christians-MacBook-Pro:debops-wordpress christianlaborde$ echo $PATH
usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
Christians-MacBook-Pro:debops-wordpress christianlaborde$ /usr/bin/env bash
bash-3.2$

**Comment by carlalexander** [comment] 2016-03-01 16:37
Can you check that you have the following in `inventory/group_vars/all/vars.yml`:

``` yml
pki_internal: False
pki_authorities: []
```

**Comment by rukawaxz** [comment] 2016-03-01 16:54
# All DebOps defaults are stored here.

# You should overwrite these values in either a group or host vars file.

ntp_timezone: 'Etc/UTC'

pki_internal: False
pki_authorities: []

**Comment by carlalexander** [comment] 2016-03-01 17:09
Ok, so the workaround doesn't work. I'll have to do more tests tonight.

**Comment by drybjed** [comment] 2016-03-01 17:17
@carlalexander I think that I know what's up. The `pki-authority sign-by-host` most likely still tries to sign certificates and fails. @rukawaxz, can you try commenting out this task in the `debops.pki` role and checking if that fixes the problem?

**Comment by carlalexander** [comment] 2016-03-01 17:46
I'm not running into any issues with bash 3.2 for some reason. Updated everything 15 minutes ago.

**Comment by rukawaxz** [comment] 2016-03-01 17:58
Sorry I am not very technical at this.
Where can I find the file I need to edit?
debops.pki?
/Users/christianlaborde/Library/Application
Support/debops/debops-playbooks/roles/debops.pki there right? I found file with many items inside
but don't know which one I have to edit

**Comment by drybjed** [comment] 2016-03-01 18:03
@rukawaxz yes, in this directory, in file `tasks/main.yml`, comment out [these lines](https://github.com/debops/ansible-pki/blob/master/tasks/main.yml#L250-L260).

**Comment by rukawaxz** [comment] 2016-03-01 18:55
I comment those lines and it ran without errors. 
Then I ran debops wordpress and got this error.

TASK [debops.mariadb : Create databases] ***************************************
fatal: [46.101.235.48]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"item": {"name": "wordpress"}, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}]}

I had same error when I tested inside a virtual machine with ubuntu before.

**Comment by rukawaxz** [comment] 2016-03-01 19:02
With -vvvv

`TASK [debops.mariadb : Create databases] ***************************************
task path: /Users/christianlaborde/Library/Application Support/debops/debops-playbooks/roles/debops.mariadb/tasks/manage_contents.yml:12
<ubuntu-debo-fra1-01> ESTABLISH SSH CONNECTION FOR USER: None
<ubuntu-debo-fra1-01> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/christianlaborde/.ansible/cp/ansible-ssh-%h-%p-%r -tt ubuntu-debo-fra1-01 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1456858859.4-242466359998451 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1456858859.4-242466359998451 )" )'
fatal: [46.101.235.48]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"item": {"name": "wordpress"}, "msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/Users/christianlaborde/.ansible/cp/ansible-ssh-ubuntu-debo-fra1-01-22-root\" does not exist\r\nssh: Could not resolve hostname ubuntu-debo-fra1-01: nodename nor servname provided, or not known\r\n", "unreachable": true}]}`

**Comment by carlalexander** [comment] 2016-03-01 19:23
@drybjed Could it be because the server is named `ubuntu-debo-fra1-01`?

**Comment by drybjed** [comment] 2016-03-01 19:27
@carlalexander The `debops.mariadb` role uses the host's `ansible_fqdn` variable to delegate the tasks to the MariaDB server if the database is on the same host. If the FQDN is not reachable from the Ansible Controller, you can override that by setting the `mariadb_delegate_to` variable to the host inventory name, that should make it work. Alternatively, fix DNS so that Ansible can reach the remote host by its FQDN.

**Comment by carlalexander** [comment] 2016-03-01 19:34
Ok, I had an issue with that in #12. I need to look at that again. I also found an issue with welcome server because it uses SSL by default.

**Comment by carlalexander** [comment] 2016-03-02 01:00
Ok, so looking at `debops.mariadb`, I pass `localhost` to `mariadb_server` by default. This makes it use `ansible_fqdn` for `mardiadb_delegate_to`. I should use  `127.0.0.1` instead right?

**Comment by carlalexander** [comment] 2016-03-02 01:15
Made some changes @rukawaxz if you want to update the project

**Comment by rukawaxz** [comment] 2016-03-02 10:51
I download project again and got this error.
Here reporting using -vvvv

TASK [debops.mariadb : Create databases] ***************************************
task path: /Users/christianlaborde/Library/Application Support/debops/debops-playbooks/roles/debops.mariadb/tasks/manage_contents.yml:12
<ubuntu-debo-fra1-01> ESTABLISH SSH CONNECTION FOR USER: None
<ubuntu-debo-fra1-01> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/christianlaborde/.ansible/cp/ansible-ssh-%h-%p-%r -tt ubuntu-debo-fra1-01 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1456914890.26-210370566675987 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1456914890.26-210370566675987 )" )'
fatal: [46.101.139.174]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"item": {"name": "wordpress"}, "msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/Users/christianlaborde/.ansible/cp/ansible-ssh-ubuntu-debo-fra1-01-22-root\" does not exist\r\nssh: Could not resolve hostname ubuntu-debo-fra1-01: nodename nor servname provided, or not known\r\n", "unreachable": true}]}

**Comment by carlalexander** [comment] 2016-03-02 13:59
Ok, so that didn't work. I'll need to do more tests. In the meantime, you can destroy the DO droplet that you have and create a new one where the hostname isn't `ubuntu-debo-fra1-01`. This should solve the issue instead of waiting for me to find a workaround. 

I'll update the Digital Ocean guide too.

![hostname](https://cloud.githubusercontent.com/assets/654684/13462346/f1dbf714-e054-11e5-9063-2bd1631dfaa0.png)

Instead of `wordpress.example.com`, use the `www.yoursite.com`.

**Comment by rukawaxz** [comment] 2016-03-02 14:50
Still same error.

```
TASK [debops.mariadb : Create databases] ***************************************
task path: /Users/christianlaborde/Library/Application Support/debops/debops-playbooks/roles/debops.mariadb/tasks/manage_contents.yml:12
<www.tiensweb.com> ESTABLISH SSH CONNECTION FOR USER: None
<www.tiensweb.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/christianlaborde/.ansible/cp/ansible-ssh-%h-%p-%r -tt www.tiensweb.com '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1456929967.86-114738198846647 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1456929967.86-114738198846647 )" )'
fatal: [46.101.98.205]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"item": {"name": "wordpress"}, "msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/Users/christianlaborde/.ansible/cp/ansible-ssh-www.tiensweb.com-22-root\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to www.tiensweb.com [104.18.49.235] port 22.\r\ndebug2: fd 5 setting O_NONBLOCK\r\ndebug1: connect to address 104.18.49.235 port 22: Operation timed out\r\ndebug1: Connecting to www.tiensweb.com [104.18.48.235] port 22.\r\ndebug2: fd 5 setting O_NONBLOCK\r\ndebug1: connect to address 104.18.48.235 port 22: Operation timed out\r\nssh: connect to host www.tiensweb.com port 22: Operation timed out\r\n", "unreachable": true}]}
```

**Comment by carlalexander** [comment] 2016-03-02 15:01
Ok, I'll run some tests today and get back to you.

**Comment by carlalexander** [comment] 2016-03-02 18:18
Ok, I can reproduce the issue with `ubuntu-debo-fra1-01`. I can't reproduce the other issue. That said, I tested www.tiensweb.com. It seems to point to cloudflare and not to Digital Ocean. Is that possible?

**Comment by carlalexander** [comment] 2016-03-02 18:36
Any idea why I'm getting a sudo password required error with `delegate_to` @drybjed?

``` console
TASK [debops.mariadb : Create databases] ***************************************
failed: [dev.carlalexander.ca -> localhost] => (item={u'name': u'dev_carlalexander_wp'}) => {"failed": true, "item": {"name": "dev_carlalexander_wp"}, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by drybjed** [comment] 2016-03-02 18:45
@carlalexander It looks like you are delegating to `localhost`, which is Ansible Controller. Do you need to provide password to `sudo` on your system?

What's the value of `mariadb_delegate_to`? Check with a `debug` task.

Check [this variable](https://github.com/debops/ansible-mariadb/blob/master/defaults/main.yml#L107-L119) documentation. I figure that the database is located on the same host as the webserver, correct? In that case, Ansible switches to `ansible_fqdn`. If you try to override it to `localhost`, it will work only if you are running Ansible on the same host. If you are doing this remotely, using `localhost` is wrong. In that case, if `ansible_fqdn` does not provide an useful value (ie. a resolvable FQDN), then try putting there `'{{ inventory_hostname }}'`, perhaps that will help. But it all depends on the location of the database relative to the webserver.

**Comment by carlalexander** [comment] 2016-03-02 19:16
I have `localhost` this time, but I tried with `127.0.0.1` with the same result.

**Comment by drybjed** [comment] 2016-03-02 19:42
@carlalexander Are you running Ansible on the same host you want to manage? Is the database server on it?

**Comment by carlalexander** [comment] 2016-03-02 20:27
No, I'm not. It's just something I'm testing. Database is on the same server as the web server with a hostname like `ubuntu-debo-fra1-01`. Trying to see what's tripping up `debops.mariadb`.

**Comment by drybjed** [comment] 2016-03-02 20:46
OK, so let's take it step by step.

First of all, why this weird setup and why can't it "just work"? The `debops.mariadb_server` and `debops.mariadb` roles work together to allow for MariaDB database to be on a different host than the application you are managing, so that you can for example set up multiple application servers in front of a database accessed remotely. But we still want to be able to easily deploy an application like WordPress with its database on the same host, which will be `localhost` relative to the application server.

(BTW, why all this? DebOps roles are supposed to be read-only so that you can easily get updates, this limits the configuration to Ansible inventory).

So, how do we combine two scenarios together? Use Ansible `delegate_to` option with a simple trick:
- if the database is detected to be on a different host, delegate to that different host;
- if the database is detected on the same host, delegate to the same host;

For the purpose, there are two variables used by `debops.mariadb` role:

The `mariadb_server` specifies the FQDN host where the database is deployed. If the database is detected to be on the same host, this will be set to `localhost` to correctly point the application to the local database;

The `mariadb_delegate_to` specifies the host we are delegating our database management tasks to (database and user creation). If the database is remote, it will point to that remote host.

BUT, if the database is on the same host as the application, we have a problem. A logical choice would be to delegate to `localhost`, but in our case, this results in Ansible trying to run the tasks on Ansible Controller, which is wrong! The database is on a different host.

So what to do now? The role, by default, will delegate the `debops.mariadb` tasks to the value of `ansible_fqdn` for that host, which is the FQDN address of the remote host. If DNS is configured correctly, and Ansible Controller sees the same address as the remote host, tasks will be delegated to the same host where our application and database is, and all works as expected.

@carlalexander Now, your case about using `127.0.0.1` for delegation was relevant when you are trying to setup a Docker container, but isn't anymore when you are trying to deploy the WordPress database on a production host. Let's see that again:
- your Ansible Controller called "alpha" tries to deploy the database on host `ubuntu-debo-fra1-01`. The `debops.mariadb` role sees that you didn't change the `mariadb_delegate_to` variable, and the database is configured on the same host as the application, so what does it do? It tells Ansible to delegate the tasks to... `ubuntu-debo-fra1-01` host. Which is correct in this case.

Except... Is `ubuntu-debo-fra1-01` resolvable by Ansible Controller? Try to run the command:

```
host ubuntu-debo-fra1-01
```

in the terminal. If you get a valid IP address, you're good.

What if you don't? As I said, try to set the `mariadb_delegate_to` variable for that host to it's `inventory_hostname` variable, perhaps that will fix the problem and tell Ansible to correctly delegate the tasks to that host. If not, try to use a FQDN which can reach that particular host.

**Comment by carlalexander** [comment] 2016-03-02 21:21
Ok, this clears things up. I'm still not sure why it doesn't work with `www.tiensweb.com` then.

**Comment by drybjed** [comment] 2016-03-02 21:51
From the Ansible output I can see the error:

```
connect to address 104.18.48.235 port 22: Operation timed out
```

Is that host reachable from the Ansible Controller?

**Comment by carlalexander** [comment] 2016-03-02 22:03
I'm not sure it is. There's cloudflare in front.

**Comment by rukawaxz** [comment] 2016-03-03 10:28
Yes cloudflare is in front of the domain. But I used digital ocean the server IP in the hosts files instead of domain.

**Comment by carlalexander** [comment] 2016-03-03 13:20
I've never tested a setup like this. My guess is this is causing issues. Ansible has your server IP because of the host file and that's the right thing to do. The problem is that only applies to the SSH connection.

Ansible is going to check the IP of `www.tiensweb.com` from the server and it'll get the cloudflare IP. That's what's causing the issue. Instead, I'd try something like this:
1. Recreate the droplet, but call it something else like `wordpress.tiensweb.com`.
2. Add a DNS entry to `wordpress.tiensweb.com` that points to the IP of the droplet.
3. Create the following file `inventory/host_vars/wordpress.tiensweb.com/vars.yml`
4. Add the following inside `vars.yml`:

``` yml
wordpress_domain: 'www.tiensweb.com'
```

**Comment by rukawaxz** [comment] 2016-03-03 17:09
TASK [debops.mariadb : Create databases] ***************************************
task path: /Users/christianlaborde/Library/Application Support/debops/debops-playbooks/roles/debops.mariadb/tasks/manage_contents.yml:12
<wordpress.tiensweb.com> ESTABLISH SSH CONNECTION FOR USER: None
<wordpress.tiensweb.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/christianlaborde/.ansible/cp/ansible-ssh-%h-%p-%r -tt wordpress.tiensweb.com '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1457018186.05-262591617798684 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1457018186.05-262591617798684 )" )'
fatal: [46.101.106.167]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"item": {"name": "wordpress"}, "msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/Users/christianlaborde/.ansible/cp/ansible-ssh-wordpress.tiensweb.com-22-root\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to wordpress.tiensweb.com [104.18.48.235] port 22.\r\ndebug2: fd 5 setting O_NONBLOCK\r\ndebug1: connect to address 104.18.48.235 port 22: Operation timed out\r\ndebug1: Connecting to wordpress.tiensweb.com [104.18.49.235] port 22.\r\ndebug2: fd 5 setting O_NONBLOCK\r\ndebug1: connect to address 104.18.49.235 port 22: Operation timed out\r\nssh: connect to host wordpress.tiensweb.com port 22: Operation timed out\r\n", "unreachable": true}]}

**Comment by carlalexander** [comment] 2016-03-03 17:11
@rukawaxz `wordpress.tiensweb.com` is still pointing to Cloudflare.

**Comment by rukawaxz** [comment] 2016-03-03 17:53
Maybe is better if you could make changes so that it only uses the server
IP without dealing with domain name? I know trellis from root does it that
way.The problem is that domain is not mine. So I am going to try latter
with a domain I have but I would need to wait 24 hours for the DNS to
change.

**Comment by carlalexander** [comment] 2016-03-04 01:36
I understand. Unfortunately, a lot of DebOps depends on having a valid domain name.

**Comment by carlalexander** [comment] 2016-03-15 10:25
Is this still an issue @rukawaxz?

**Comment by carlalexander** [comment] 2016-03-25 02:41
Going to close this, but please reopen if you're still having issues :smile:

**Closed as completed by carlalexander** 2016-03-25 02:41 UTC
