### ISSUE TITLE
We did not find Varnish active for this domain

### ISSUE THREAD

**Issue by gleert** [carlalexander/debops-wordpress#163] opened 2017-05-31 22:44 UTC
I am getting the error "We did not find Varnish active for this domain." in the "Varnish HTTP Purge" plugin...

![screen shot 2017-06-01 at 00 35 30](https://cloud.githubusercontent.com/assets/1012430/26657332/7edaa23a-4663-11e7-8a1c-455e098052cb.png)

I have followed the following instructions https://github.com/carlalexander/debops-wordpress/wiki/How-to-configure-Varnish

Varnish is running:

![screen shot 2017-06-01 at 00 41 03](https://cloud.githubusercontent.com/assets/1012430/26657341/8ce16986-4663-11e7-929b-8ccb74b8ea56.png)

**Comment by wpbullet** [comment] 2017-05-31 23:08
That site is likely looking for the X-Varnish header

**Comment by carlalexander** [comment] 2017-06-03 22:55
What version of the plugin are you using?

**Comment by gleert** [comment] 2017-06-03 23:00
I am using Version 4.1.1

**Comment by carlalexander** [comment] 2017-06-03 23:02
Ok, I updated and I'm seeing it. Varnish is active, but the plugin was designed with Dreamhost in mind so there are differences in the setup. I'll need to look into it to see what it expects to get everything to be green.

**Comment by gleert** [comment] 2017-06-03 23:04
Please let me know how to solve this, once you have been able to look at it... Thanks in advance

**Comment by carlalexander** [comment] 2017-06-03 23:05
Yup, but you should know that this doesn't mean that the plugin doesn't work. It just wasn't designed to detect the way DebOps setups Varnish. 😃

**Comment by gleert** [comment] 2017-06-04 12:15
Ok, but it's not emptying the cache for me...

**Comment by carlalexander** [comment] 2017-06-08 07:56
You might still see `HIT` even if you purge the cache. That's because the varnish `obj.hits` doesn't get reset the same way anymore when you do a ban. You can see an explanation [here](https://github.com/mattiasgeniar/varnish-4.0-configuration-templates/blob/master/default.vcl#L363-L365). That said, the bans do work and you should see the reset if you check the network tab in your dev tools.

**Comment by gleert** [comment] 2017-06-08 09:41
The problem is not the `HIT`, it's the fact that the content of the page isn't updating....

**Comment by carlalexander** [comment] 2017-06-09 09:26
Can you give me an example of a page?

**Comment by carlalexander** [comment] 2017-07-24 01:13
Going to close this for now. Feel free to reopen if you have more details about the issue @gleert 😃

**Closed as completed by carlalexander** 2017-07-24 01:13 UTC
Labels: awaiting feedback
