### ISSUE TITLE
Updating ssl certificates

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#107] opened 2016-10-25 11:23 UTC
Hi Carl,

i am finding it difficult to update the ssl certificates. i cannot find the certbot-auto executable.
Could you point me in the right direction?

**Comment by carlalexander** [comment] 2016-10-25 21:28
What do you mean upgrade certificates? Replace existing ones with new ones?

**Comment by cezarneaga** [comment] 2016-10-25 21:46
No. got a certificates expiring notice. They need renewing. Usually a simple `certbot-auto renew` solves it.

**Comment by carlalexander** [comment] 2016-10-25 23:23
Sorry, I wasn't clear. Which type of certificate are we talking about? `manual`, `letsencrypt`, `selfsigned`?

**Comment by cezarneaga** [comment] 2016-10-26 04:20
letsencrypt

**Comment by carlalexander** [comment] 2016-10-26 23:59
Hmmm it should update automatically. That's how `debops-pki` configures it. Is there an error log in `/etc/pki/realms/yourdomain.com/acme/`?

**Comment by cezarneaga** [comment] 2016-10-27 04:49
nope. no error_log there. maybe it renewed. it just does it after letsencrypt decides to send an email to notify. maybe we could just make the renewal happen more often.

**Comment by carlalexander** [comment] 2016-10-28 12:45
I'm not sure what the interval is for the renewal. I don't even have let's encrypt setup to send me emails. It's just been doing it lol.

It's possible that Let's Encrypt expects a different setup than what `debops.pki` is doing. And that's why you're getting an email. It's check your certificate expiry date and see if it changes over time.

**Comment by cezarneaga** [comment] 2016-10-28 13:19
cheers.
thanks!

**Comment by zedrickvillas** [comment] 2016-11-13 10:11
Please close this ticket if the issue is resolved. Thanks :D

**Comment by cezarneaga** [comment] 2017-01-18 09:45
this is still an issue at least on ubuntu 14.04 setup. certificates do not renew.

**Comment by carlalexander** [comment] 2017-01-18 12:34
Is there an `error.log` in `/etc/pki/realms/<domain>/acme`?

**Comment by cezarneaga** [comment] 2017-01-18 12:47
nope. no error.log

**Comment by carlalexander** [comment] 2017-01-18 12:56
Can you try to run `/usr/local/lib/pki/pki-realm schedule`? I might have to defer to @drybjed for this since I don't understand everything that goes on in `debops.pki`. I'm not sure why it wouldn't renew.

**Comment by cezarneaga** [comment] 2017-01-18 13:11
`pki-realm: 7: set: Illegal option -o pipefail`

**Comment by carlalexander** [comment] 2017-01-18 14:57
Was that with `sudo`? Sorry didn't put it in the comment 😢

**Comment by cezarneaga** [comment] 2017-01-18 15:05
yes yes

**Comment by carlalexander** [comment] 2017-01-18 18:00
Weird, that might be why it doesn't renew. At this point, I think you should create a ticket for it in [`debops.pki`](https://github.com/debops/ansible-pki) and see what @drybjed thinks.

**Closed as completed** 2017-02-24 10:22 UTC

**Comment by carlalexander** [comment] 2017-02-24 13:14
Did you find the issue @cezarneaga?

**Comment by cezarneaga** [comment] 2017-02-24 14:40
no. i just thought it might be obsolete as now there are other versions already up that might have solved it
